CREATE TABLE `BUILDING` (
	CODE VARCHAR(10) PRIMARY KEY,
	NAME VARCHAR(15)
);

CREATE TABLE `TIMETABLE` (
	CODE VARCHAR(10) PRIMARY KEY,
	DAY VARCHAR(5),
	STARTTIME TIME,
	ENDTIME TIME
);

CREATE TABLE `CLASSROOM` (
	CODE VARCHAR(10),
	NAME VARCHAR(20),
	BUILDINGCODE VARCHAR(10) REFERENCES BUILDING(CODE) 
);

CREATE TABLE `BOOK`(
	BOOKNUM INT AUTO_INCREMENT PRIMARY KEY,
	CLASSROOMCODE VARCHAR(10) REFERENCES CLASSROOM(CODE),
	TIMETABLECODE VARCHAR(10) REFERENCES TIMETABLE(CODE),
	BOOKER VARCHAR(5) UNIQUE,
	UNIQUE(CLASSROOMCODE, TIMETABLECODE)
);