SELECT YEAR(SALES_DATE) YEAR, 
    MONTH(SALES_DATE) MONTH, 
    COUNT(DISTINCT SALE.USER_ID) PUCHASED_USERS,
    ROUND(COUNT(DISTINCT SALE.USER_ID) / SUB.CNT,1) PUCHASED_RATIO
FROM ONLINE_SALE SALE
JOIN (SELECT COUNT(*) CNT FROM USER_INFO WHERE YEAR(JOINED)='2021') SUB
WHERE SALE.USER_ID IN (SELECT USER_ID FROM USER_INFO WHERE YEAR(JOINED)='2021')
GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE)
;


