SELECT CAST(SUBSTRING(START_DATE,6,2) AS UNSIGNED) AS MONTH, CAR_ID, COUNT(CAR_ID) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE SUBSTRING(START_DATE,1,7) BETWEEN '2022-08' AND '2022-10'
AND CAR_ID IN (SELECT CAR_ID C 
                FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                WHERE SUBSTRING(START_DATE,1,7) BETWEEN '2022-08' AND '2022-10'
                GROUP BY CAR_ID 
                HAVING COUNT(CAR_ID)>=5)
GROUP BY CAR_ID, MONTH
ORDER BY MONTH, CAR_ID DESC
