SELECT C.CAR_ID, C.CAR_TYPE,
        ROUND(C.DAILY_FEE * 30 * (100-CAST(SUBSTR(P.DISCOUNT_RATE,-1) AS UNSIGNED))/100,0) AS FEE
FROM CAR_RENTAL_COMPANY_CAR C
INNER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
ON C.CAR_TYPE = P.CAR_TYPE AND P.DURATION_TYPE REGEXP '30'
WHERE C.CAR_TYPE IN ('세단','SUV')
    # AND C.DAILY_FEE * 30 * (100-CAST(SUBSTR(P.DISCOUNT_RATE,-1) AS UNSIGNED))/100 BETWEEN 500000 AND 1999999
    AND CAR_ID NOT IN (SELECT CAR_ID 
                        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
                        WHERE '2022-11' BETWEEN SUBSTR(START_DATE,1,7) AND SUBSTR(END_DATE,1,7))
HAVING FEE BETWEEN 500000 AND 2000000
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC
