-- 게시글제목, 게시글id, 댓글id, 댓글작성자 id, 댓글내용, 댓글작성일
-- "게시글"이 2022년 10월에 게시된 것 조회
-- 댓글작성일 기준 오름차순, 게시글 제목 기준 오름차순
SELECT B.TITLE, B.BOARD_ID, R.REPLY_ID, R.WRITER_ID, R.CONTENTS, DATE_FORMAT(R.CREATED_DATE,'%Y-%m-%d') AS CREATED_DATE
FROM USED_GOODS_REPLY R
INNER JOIN USED_GOODS_BOARD AS B
USING(BOARD_ID)
WHERE DATE_FORMAT(B.CREATED_DATE,'%Y-%m') = '2022-10'
ORDER BY R.CREATED_DATE ASC, B.TITLE ASC