SELECT PRODUCT_CODE, (SUM(SALES_AMOUNT) * PRICE) AS SALES
FROM PRODUCT
INNER JOIN OFFLINE_SALE
ON OFFLINE_SALE.PRODUCT_ID = PRODUCT.PRODUCT_ID
GROUP BY OFFLINE_SALE.PRODUCT_ID
ORDER BY SALES DESC, PRODUCT_CODE
;