SELECT SUB.FOOD_TYPE, REST_ID, REST_NAME, SUB.FAVORITES
FROM REST_INFO INFO
JOIN (
    SELECT FOOD_TYPE, MAX(FAVORITES) FAVORITES
    FROM REST_INFO
    GROUP BY FOOD_TYPE
) AS SUB
ON SUB.FOOD_TYPE = INFO.FOOD_TYPE AND SUB.FAVORITES = INFO.FAVORITES
ORDER BY FOOD_TYPE DESC
;