SELECT MEM.MEMBER_NAME, REST.REVIEW_TEXT, DATE_FORMAT(REST.REVIEW_DATE,'%Y-%m-%d') AS REVIEW_DATE
FROM MEMBER_PROFILE MEM
JOIN REST_REVIEW REST
ON REST.MEMBER_ID = MEM.MEMBER_ID
JOIN 
    (SELECT MEMBER_ID, COUNT(*) AS CNT
     FROM REST_REVIEW
     GROUP BY MEMBER_ID
     ORDER BY CNT DESC
     LIMIT 1
    ) AS SUB
ON REST.MEMBER_ID = SUB.MEMBER_ID
ORDER BY REST.REVIEW_DATE
;

# 아래도 가능하다.
SELECT MEM.MEMBER_NAME, REST.REVIEW_TEXT, DATE_FORMAT(REST.REVIEW_DATE,'%Y-%m-%d') AS REVIEW_DATE
FROM MEMBER_PROFILE MEM
JOIN REST_REVIEW REST
ON REST.MEMBER_ID = MEM.MEMBER_ID
WHERE REST.MEMBER_ID = 
    (SELECT MEMBER_ID
     FROM REST_REVIEW
     GROUP BY MEMBER_ID
     ORDER BY COUNT(*) DESC
     LIMIT 1
    )
ORDER BY REST.REVIEW_DATE
;