SELECT SUB.CATEGORY, PRICE AS MAX_PRICE, PRODUCT_NAME
FROM FOOD_PRODUCT
JOIN (
    SELECT CATEGORY, MAX(PRICE) P
    FROM FOOD_PRODUCT
    GROUP BY CATEGORY
    HAVING CATEGORY IN ('과자', '국', '김치', '식용유')
    ) AS SUB
ON SUB.CATEGORY = FOOD_PRODUCT.CATEGORY AND SUB.P = PRICE
ORDER BY MAX_PRICE DESC
;