SELECT FR.PRODUCT_ID, FR.PRODUCT_NAME, SUM(FO.AMOUNT * FR.PRICE) AS TOTAL_SALES
FROM FOOD_PRODUCT FR
JOIN FOOD_ORDER FO
ON FR.PRODUCT_ID = FO.PRODUCT_ID
WHERE DATE_FORMAT(FO.PRODUCE_DATE, '%Y-%m') = '2022-05'
GROUP BY FO.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, FR.PRODUCT_ID
;
